// src/data/mockJobs.js
const mockJobs = [
    {
      id: 1,
      title: 'Software Engineer',
      company: 'Google',
      location: 'Mountain View, CA',
      description: 'Build scalable web applications...',
      salary: '120000',
    },
    {
      id: 2,
      title: 'Product Manager',
      company: 'Facebook',
      location: 'Menlo Park, CA',
      description: 'Lead cross-functional teams to build products...',
      salary: '130000',
    },
    {
      id: 3,
      title: 'Data Scientist',
      company: 'Twitter',
      location: 'San Francisco, CA',
      description: 'Analyze data and build predictive models...',
      salary: '115000',
    },
    {
      id: 4,
      title: 'UX Designer',
      company: 'Apple',
      location: 'Cupertino, CA',
      description: 'Design user-friendly interfaces...',
      salary: '110000',
    },
    {
      id: 5,
      title: 'Marketing Specialist',
      company: 'Amazon',
      location: 'Seattle, WA',
      description: 'Develop and implement marketing strategies...',
      salary: '105000',
    },
    {
      id: 6,
      title: 'Backend Developer',
      company: 'Microsoft',
      location: 'Redmond, WA',
      description: 'Build and maintain server-side logic...',
      salary: '125000',
    },
    {
      id: 7,
      title: 'Frontend Developer',
      company: 'Netflix',
      location: 'Los Gatos, CA',
      description: 'Develop and maintain web applications...',
      salary: '118000',
    },
    {
      id: 8,
      title: 'DevOps Engineer',
      company: 'LinkedIn',
      location: 'Sunnyvale, CA',
      description: 'Ensure the reliability of infrastructure...',
      salary: '122000',
    },
    {
      id: 9,
      title: 'Full Stack Developer',
      company: 'Adobe',
      location: 'San Jose, CA',
      description: 'Work on both frontend and backend...',
      salary: '124000',
    },
    {
      id: 10,
      title: 'System Administrator',
      company: 'Oracle',
      location: 'Redwood City, CA',
      description: 'Manage and configure company systems...',
      salary: '95000',
    },
    {
      id: 11,
      title: 'AI Researcher',
      company: 'OpenAI',
      location: 'San Francisco, CA',
      description: 'Research and develop AI algorithms...',
      salary: '140000',
    },
    {
      id: 12,
      title: 'Sales Manager',
      company: 'Salesforce',
      location: 'San Francisco, CA',
      description: 'Drive sales growth and manage the sales team...',
      salary: '130000',
    },
    {
      id: 13,
      title: 'Business Analyst',
      company: 'IBM',
      location: 'Armonk, NY',
      description: 'Analyze business needs and propose solutions...',
      salary: '115000',
    },
    {
      id: 14,
      title: 'Network Engineer',
      company: 'Cisco',
      location: 'San Jose, CA',
      description: 'Design and implement network solutions...',
      salary: '120000',
    },
    {
      id: 15,
      title: 'Cybersecurity Specialist',
      company: 'Symantec',
      location: 'Mountain View, CA',
      description: 'Protect systems from cybersecurity threats...',
      salary: '130000',
    },
  ];
  
  export default mockJobs;
  